language: c++
sudo: required
dist: trusty

addons: &addons
  apt:
    packages: &packages
      - libzmq3-dev
      - libzmq3
      - automake
      - libtool
      - libboost1.55-all-dev
      - vlc-nox
      - libvlc-dev
      - libasound2
      - libasound2-dev
      - libjack-jackd2-dev
      - jackd2
      - libmagickwand-dev

compiler:
  - gcc
  - clang

script:
  - |
    pushd /tmp
    git clone https://github.com/Opendigitalradio/ka9q-fec.git
    cd ka9q-fec
    mkdir build
    cd build
    cmake ..
    make
    sudo make install
    popd
  - |
    ./bootstrap
    ./configure
    make
  - |
    ./configure --enable-vlc
    make
  - |
    ./configure --enable-alsa
    make
  - |
    ./configure --enable-jack
    make
  - |
    ./configure --enable-alsa --enable-jack --enable-vlc
    make

